"use client"
import { Inter } from 'next/font/google'
import { FirebaseAuthProvider } from './Element/ContextGiver'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </head>
      <body className={inter.className}>
        <FirebaseAuthProvider>
          {children}
        </FirebaseAuthProvider>
      </body>
    </html>
  )
}
